// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwbhlmfyswfeukpzbhmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3YmhsbWZ5c3dmZXVrcHpiaG1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTQ5MDAsImV4cCI6MjA2MjEzMDkwMH0.la--nA2f9bm5W8NX-_pk_ww5FOqhfJaxCvjW4D0xDtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);